input_data:
  file_path: "/var/localfs/working2/jradig/projects/snakemake_pipeline/data/kang.h5ad"

experiment:
  condition: "condition"
  condition_control: "control"
  condition_stimulated: "stimulated"
  batch: "cell_type"
  target: "CD8T"
  experiment_name: "kang_latent"
  output_dir: "/var/localfs/working2/jradig/projects/snakemake_pipeline/results"
